baseURL = "/"
languageCode = "en-us"
title = "Acorn Property Management"
themesDir = "themes"
theme = "hugo-hero-theme-custom"
publishDir = "docs"

# ---------------------------------------------------------------------------------
# Site Params
# ---------------------------------------------------------------------------------
[params]
  google_analytics_id="UA-198337024-1"
  statement = "fair housing"

  [params.homepage_meta_tags]
    meta_description = "Full-service property management offerings for residential properties in Columbus, Ohio."
    meta_og_title = "Acorn Property Management"
    meta_og_type = "website"
    meta_og_url = "https://www.acornmgt.com/"
    meta_og_image = "https://www.acornmgt.com/images/opengraph-landscape.png"
    meta_og_description = "Full-service property management offerings for residential properties in Columbus, Ohio."
    meta_twitter_card = "summary"
    meta_twitter_site = "@"
    meta_twitter_creator = "@"

# ---------------------------------------------------------------------------------
# Main Menu
# ---------------------------------------------------------------------------------
[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

#[[menu.main]]
#	name = "Services"
#	url = "/services/"
#    weight = 2

[[menu.main]]
    name = "Available"
    url = "https://acornmgt.managebuilding.com"
    weight = 3

[[menu.main]]
    name = "Residents"
    url = "https://acornmgt.managebuilding.com/resident/portal"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

# ---------------------------------------------------------------------------------
# Permalinks
# ---------------------------------------------------------------------------------
[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
